version: '3'
services:
  dependency_parser:
    image: "kazhar/finnish-dep-parser"
    ports:
     - "9876:9876"
  summarization_app:
    build: .
    ports:
     - "5000:5000"
     - "7000:7000"
    environment:
    - FLASK_ENV=production
    - APIURL=http://127.0.0.1:5000