version: '3'
services:
  dependency_parser:
    image: "kazhar/finnish-dep-parser"
    ports:
     - "9876"
  server:
    build: .
    image: "samutamm/summarization_server"
    ports:
     - "5000:5000" # HOST_PORT : CONTAINER_PORT. Host port can be changed to anything, but it should correspond APIURL environment variable
     - "7000:7000" # HOST_PORT : CONTAINER_PORT. Host port can be anything.
    environment:
    - FLASK_ENV=production
    - APIURL=http://127.0.0.1:5000 # This should point towards api that is exposed from port 5000 in container.